"""
shared_corpus_metadata.py - Enterprise HR Policy Documents & Golden Queries Metadata
Shared across Scenarios 1 to 5 and the Unified Portal.
"""

DOCUMENTS_ID = [
    {
        "filename": "01_Kebijakan_Cuti_Karyawan.pdf",
        "title": "Kebijakan Cuti Karyawan",
        "code": "HC-KBJ-011/2026",
        "category": "Cuti & Izin",
        "pages": 2,
        "description": "Cuti tahunan bertingkat (12-18 hari), cuti bersama, cuti melahirkan (3 bulan), cuti pendampingan persalinan (5 hari kerja), dan cuti besar 1 bulan.",
        "test_target": "Pencarian Semantik Murni (Q1-ID)",
    },
    {
        "filename": "02_Panduan_Tunjangan_dan_Kesehatan_2026.pdf",
        "title": "Panduan Tunjangan dan Kesehatan 2026",
        "code": "HC-TNJ-002/2026",
        "category": "Kompensasi & Manfaat",
        "pages": 2,
        "description": "Tabel manfaat plafon rawat inap, rawat jalan, persalinan normal/caesar, kacamata per level jabatan (Staf, Supervisor, Manajer, Direktur), BPJS, dan THR.",
        "test_target": "Parsing Data Tabel Multikolom (Q3-ID)",
    },
    {
        "filename": "03_Kebijakan_Perjalanan_Dinas_dan_Reimburse.pdf",
        "title": "Kebijakan Perjalanan Dinas & Reimburse",
        "code": "FIN-KBJ-402/2026",
        "category": "Keuangan & Operasional",
        "pages": 2,
        "description": "Surat Perintah Perjalanan Dinas (SPPD), Formulir PDN-402B (batas pengajuan 14 hari kalender), uang harian wilayah I-III, dan aturan kuitansi.",
        "test_target": "Pencarian Kata Kunci & Kode Formulir (Q2-ID)",
    },
    {
        "filename": "04_FAQ_WFH_WFA_dan_Tunjangan_Peralatan.pdf",
        "title": "FAQ WFH, WFA, dan Tunjangan Peralatan",
        "code": "HC-FAQ-220/2026",
        "category": "Fleksibilitas Kerja",
        "pages": 2,
        "description": "Batas WFH (2 hari/minggu), WFA dalam negeri (maksimal 20 hari kerja/tahun, pengajuan H-7), WFA luar negeri (10 hari, izin Direktur/IT), fasilitas kerja.",
        "test_target": "Penalaran Agentik & Transaksional (Q4-ID)",
    },
    {
        "filename": "05_Kebijakan_Kompensasi_Lembur_dan_THR.pdf",
        "title": "Kebijakan Kompensasi, Lembur, dan THR",
        "code": "HC-KBJ-015/2026",
        "category": "Remunerasi & Lembur",
        "pages": 2,
        "description": "Formula upah lembur PP 35/2021 (1/173 x gaji pokok), Form OT-201, batas pembayaran THR H-7, dan bonus kinerja tahunan (KPI 1-5).",
        "test_target": "Kalkulasi Regulasi Ketenagakerjaan (Q5-ID)",
    },
    {
        "filename": "06_Kode_Etik_Anti_Korupsi_dan_Whistleblowing.pdf",
        "title": "Kode Etik, Anti-Korupsi & Whistleblowing",
        "code": "LEG-ETH-001/2026",
        "category": "Kepatuhan & Tata Kelola",
        "pages": 2,
        "description": "Ketentuan gratifikasi batas Rp 500.000,-, pelaporan Form ETH-101 (3 hari kerja), kanal whistleblowing etika@cymbal.co.id, dan perlindungan pelapor.",
        "test_target": "Kepatuhan Hukum & Saluran Pelaporan (Q6-ID)",
    },
    {
        "filename": "07_Panduan_Manajemen_Kinerja_dan_Promosi.pdf",
        "title": "Panduan Manajemen Kinerja & Promosi",
        "code": "HC-PRF-301/2026",
        "category": "Pengembangan Karier",
        "pages": 2,
        "description": "Skala penilaian 1-5, matriks kenaikan gaji merit (3,5% - 15%), dossier promosi Form PRM-301, dan protokol evaluasi PIP 60 hari kalender (Form PIP-401).",
        "test_target": "Matriks Merit & Protokol PIP (Q7-ID)",
    },
    {
        "filename": "08_Kebijakan_Keamanan_Informasi_BYOD_dan_Privasi_Data.pdf",
        "title": "Keamanan Informasi, BYOD & Privasi Data",
        "code": "SEC-POL-501/2026",
        "category": "Keamanan Siber & Privasi",
        "pages": 2,
        "description": "UU PDP 27/2022 & ISO 27001, standar BYOD (Google MDM, disk encryption), password minimal 14 karakter rotasi 90 hari, auto-lock 5 menit, Form SEC-101.",
        "test_target": "Standar Keamanan & Perlindungan Data (Q8-ID)",
    },
    {
        "filename": "09_Program_Pengembangan_Karyawan_dan_Beasiswa.pdf",
        "title": "Pengembangan Karyawan & Beasiswa S2",
        "code": "LND-POL-201/2026",
        "category": "Pelatihan & Pendidikan",
        "pages": 2,
        "description": "Anggaran pelatihan Rp 15 jt/tahun/karyawan, bantuan beasiswa S2 hingga 75% biaya kuliah, rumus ikatan dinas 2n+1 tahun, Form LND-201.",
        "test_target": "Formula Ikatan Dinas & Anggaran L&D (Q9-ID)",
    },
    {
        "filename": "10_Prosedur_Terminasi_Resignasi_dan_Pesangon.pdf",
        "title": "Prosedur Terminasi, Resignasi & Pesangon",
        "code": "HC-OFF-101/2026",
        "category": "Offboarding & Terminasi",
        "pages": 2,
        "description": "Notice period 30 hari via Form OFF-301, tabel uang pesangon & UPMK sesuai PP 35/2021 hingga 19 bulan gaji, formula UPH cuti, paklaring H+7.",
        "test_target": "Formula Pesangon & Ketentuan Pemutusan Hubungan Kerja (Q10-ID)",
    },
]

DOCUMENTS_EN = [
    {
        "filename": "01_Global_PTO_and_Leave_Policy.pdf",
        "title": "Global PTO & Leave Policy",
        "code": "GL-PTO-001/2026",
        "category": "Time Off & Leave",
        "pages": 2,
        "description": "PTO accrual tiers by tenure (15-25 days), carryover limits, parental leave (16 weeks paid for primary caregivers, 4 weeks secondary), bereavement.",
        "test_target": "Pure Semantic Search (Q1)",
    },
    {
        "filename": "02_2026_Benefits_and_Healthcare_Guide.pdf",
        "title": "2026 Benefits & Healthcare Guide",
        "code": "GL-BEN-2026",
        "category": "Health & Benefits",
        "pages": 2,
        "description": "Multi-column comparison of HDHP vs PPO medical plans (deductibles, out-of-pocket maximums, employer HSA contributions), dental, and vision.",
        "test_target": "Multi-Column Table Parsing (Q3)",
    },
    {
        "filename": "03_Expense_and_Travel_Reimbursement_Policy.pdf",
        "title": "Expense & Travel Reimbursement Policy",
        "code": "GL-EXP-402/2026",
        "category": "Finance & Travel",
        "pages": 2,
        "description": "Form EXP-402B for expenses exceeding $500, 30 calendar day submission deadline, per-diem caps by city tier, and VP approval thresholds.",
        "test_target": "Exact Form Codes & Numbers (Q2)",
    },
    {
        "filename": "04_Remote_Work_and_Equipment_Stipend_FAQ.pdf",
        "title": "Remote Work & Equipment Stipend FAQ",
        "code": "GL-RMT-220/2026",
        "category": "Workplace Flexibility",
        "pages": 2,
        "description": "Hybrid work schedules, home office stipend ($1,000 every 3 years), international work-from-anywhere rules (up to 20 workdays/year, 14 days advance notice).",
        "test_target": "Agentic & Transactional Reasoning (Q4)",
    },
    {
        "filename": "05_Global_Compensation_Overtime_and_Bonus_Plan.pdf",
        "title": "Global Compensation, Overtime & Bonus Plan",
        "code": "GL-CMP-105/2026",
        "category": "Total Rewards & Compensation",
        "pages": 2,
        "description": "FLSA Non-Exempt overtime at 1.5x regular rate for >40 hrs, Short-Term Incentive (STI) bonus formula, 4-year RSU vesting with 1-year cliff, Form CMP-101.",
        "test_target": "FLSA Overtime & Equity Vesting (Q5)",
    },
    {
        "filename": "06_Global_Code_of_Conduct_Anti_Corruption_and_Whistleblowing.pdf",
        "title": "Global Code of Conduct & Whistleblowing",
        "code": "GL-ETH-001/2026",
        "category": "Ethics & Compliance",
        "pages": 2,
        "description": "FCPA & UK Bribery Act, gift threshold $100 (disclose $100-$250 via Form ETH-101, >$250 prohibited), 24/7 EthicsPoint hotline 1-800-461-9330.",
        "test_target": "FCPA Compliance & Ethics Hotline (Q6)",
    },
    {
        "filename": "07_Performance_Calibration_Promotion_and_PIP_Guidelines.pdf",
        "title": "Performance Calibration, Promotions & PIP",
        "code": "GL-PRF-301/2026",
        "category": "Performance & Talent",
        "pages": 2,
        "description": "5-tier rating scale, compa-ratio merit matrices (3%-12%), promotion dossier Form PRM-301 (min 12 mos tenure), and formal 60-day PIP via Form PIP-401.",
        "test_target": "Calibration Ratings & Merit Increase (Q7)",
    },
    {
        "filename": "08_Information_Security_BYOD_and_Acceptable_Use_Policy.pdf",
        "title": "Information Security, BYOD & Acceptable Use",
        "code": "GL-SEC-501/2026",
        "category": "Cybersecurity & Data Privacy",
        "pages": 2,
        "description": "SOC2 & GDPR controls, MDM enrollment, BitLocker/FileVault, 14-char password with 90-day expiry, 5-minute inactivity lock, 1-hour breach SLA, Form SEC-101.",
        "test_target": "SOC2 Compliance & Incident SLAs (Q8)",
    },
    {
        "filename": "09_Learning_Development_and_Tuition_Assistance_Program.pdf",
        "title": "Learning & Tuition Assistance Program",
        "code": "GL-LND-201/2026",
        "category": "Talent Development",
        "pages": 2,
        "description": "$2,500 individual annual stipend via Form LND-201, up to $5,250 tax-free tuition reimbursement under IRS Section 127, 12-month retention agreement.",
        "test_target": "IRS Sec 127 & Retention Covenants (Q9)",
    },
    {
        "filename": "10_Offboarding_Severance_and_Separation_Policy.pdf",
        "title": "Offboarding, Severance & Separation Policy",
        "code": "GL-OFF-101/2026",
        "category": "Offboarding & Transitions",
        "pages": 2,
        "description": "2-4 weeks written notice Form OFF-301, severance formula (2 weeks base/year service, 4-26 weeks cap), 3 months COBRA subsidy, accrued PTO payout formula.",
        "test_target": "Severance Formula & COBRA Subsidies (Q10)",
    },
]

GOLDEN_QUERIES_ID = [
    {
        "id": "Q1-ID",
        "category": "Pencarian Semantik Murni",
        "title": "Cuti Pendampingan Istri Melahirkan",
        "query": "Istri saya baru saja melahirkan. Saya dapat libur berapa hari?",
        "source_doc": "01_Kebijakan_Cuti_Karyawan.pdf",
        "solution": "Cuti pendampingan persalinan diberikan selama 5 hari kerja (Bab IV Pasal 7).",
    },
    {
        "id": "Q2-ID",
        "category": "Kata Kunci & Kode Formulir",
        "title": "Formulir PDN-402B & SPPD",
        "query": "Formulir PDN-402B itu untuk apa, dan berapa lama batas pengajuannya setelah SPPD selesai?",
        "source_doc": "03_Kebijakan_Perjalanan_Dinas_dan_Reimburse.pdf",
        "solution": "Formulir Pertanggungjawaban Biaya Perjalanan Dinas, batas penyerahan 14 hari kalender.",
    },
    {
        "id": "Q3-ID",
        "category": "Data Tabel Multikolom",
        "title": "Plafon Staf vs Manajer",
        "query": "Bandingkan plafon rawat jalan per tahun dan tunjangan persalinan caesar antara level Staf dan Manajer.",
        "source_doc": "02_Panduan_Tunjangan_dan_Kesehatan_2026.pdf",
        "solution": "Rawat Jalan: Staf Rp 7,5 jt vs Manajer Rp 15 jt; Caesar: Staf Rp 18 jt vs Manajer Rp 30 jt.",
    },
    {
        "id": "Q4-ID",
        "category": "Penalaran Agentik & Transaksional",
        "title": "WFA Bali + Saldo Cuti EMP-1042",
        "query": "Saya karyawan EMP-1042. Boleh nggak saya WFA dari Bali 15 hari kerja bulan depan, dan sisa cuti tahunan saya cukup nggak untuk ambil 5 hari cuti tambahan di sana?",
        "source_doc": "04_FAQ_WFH_WFA_dan_Tunjangan_Peralatan.pdf + HRIS DB",
        "solution": "Boleh WFA (kuota tersisa 16 dari maks 20 hari, pengajuan H-7). Cuti cukup (sisa cuti 7 hari, butuh 5 hari).",
    },
    {
        "id": "Q5-ID",
        "category": "Kompensasi & Lembur",
        "title": "Rumus Upah Lembur & Batas THR",
        "query": "Bagaimana rumus perhitungan upah lembur karyawan di hari kerja biasa, dan kapan batas akhir pembayaran THR keagamaan?",
        "source_doc": "05_Kebijakan_Kompensasi_Lembur_dan_THR.pdf",
        "solution": "Jam ke-1: 1,5 × (1/173 × Gaji Pokok), jam ke-2+: 2,0 × (1/173 × Gaji Pokok). Form lembur OT-201. THR wajib dibayar paling lambat H-7 sebelum Hari Raya.",
    },
    {
        "id": "Q6-ID",
        "category": "Kode Etik & Gratifikasi",
        "title": "Batas Nilai Hadiah & Form Gratifikasi",
        "query": "Berapa batas maksimal nominal hadiah dari vendor yang boleh diterima, dan formulir apa yang wajib diisi untuk melaporkannya?",
        "source_doc": "06_Kode_Etik_Anti_Korupsi_dan_Whistleblowing.pdf",
        "solution": "Batas maksimal Rp 500.000,- per vendor/tahun. Wajib dilaporkan melalui Form ETH-101 maksimal 3 hari kerja ke Komite Etik. Whistleblower via etika@cymbal.co.id.",
    },
    {
        "id": "Q7-ID",
        "category": "Manajemen Kinerja & PIP",
        "title": "Kenaikan Merit Rating 5 & Durasi PIP",
        "query": "Berapa persentase kenaikan gaji merit untuk karyawan dengan rating kinerja 5, dan berapa lama durasi program PIP?",
        "source_doc": "07_Panduan_Manajemen_Kinerja_dan_Promosi.pdf",
        "solution": "Rating 5 mendapatkan kenaikan merit 10,0% - 15,0%. Durasi PIP tepat 60 hari kalender via Form PIP-401 dengan evaluasi berkala hari ke-30 dan ke-60.",
    },
    {
        "id": "Q8-ID",
        "category": "Keamanan Informasi & BYOD",
        "title": "Standar BYOD & Timeout Auto-Lock",
        "query": "Apa syarat spesifikasi keamanan untuk laptop pribadi (BYOD) dan berapa batas waktu auto-lock layar yang diwajibkan?",
        "source_doc": "08_Kebijakan_Keamanan_Informasi_BYOD_dan_Privasi_Data.pdf",
        "solution": "Pendaftaran Google MDM, enkripsi BitLocker/FileVault, password minimal 14 karakter (rotasi 90 hari), dan timeout auto-lock layar maksimal 5 menit.",
    },
    {
        "id": "Q9-ID",
        "category": "Pengembangan & Beasiswa S2",
        "title": "Anggaran Pelatihan & Ikatan Dinas Beasiswa",
        "query": "Berapa plafon anggaran pelatihan tahunan karyawan, dan apa rumus masa ikatan dinas bagi penerima beasiswa S2?",
        "source_doc": "09_Program_Pengembangan_Karyawan_dan_Beasiswa.pdf",
        "solution": "Plafon pelatihan Rp 15.000.000,- per tahun per karyawan via Form LND-201. Ikatan dinas beasiswa S2 berdurasi 2n + 1 tahun (beasiswa 2 tahun = ikatan 5 tahun).",
    },
    {
        "id": "Q10-ID",
        "category": "Resignasi & Pesangon",
        "title": "Notice Period Resign & Formula UPH Cuti",
        "query": "Berapa hari masa pemberitahuan (notice period) pengunduran diri bagi staf, dan bagaimana rumus uang penggantian hak cuti?",
        "source_doc": "10_Prosedur_Terminasi_Resignasi_dan_Pesangon.pdf",
        "solution": "Notice period minimal 30 hari kalender via Form OFF-301. Rumus UPH Cuti: (Sisa Hari Cuti / 21) × Gaji Pokok Bulanan. Pesangon & UPMK mengacu PP 35/2021 hingga 19 bulan gaji.",
    },
]

GOLDEN_QUERIES_EN = [
    {
        "id": "Q1",
        "category": "Pure Semantic Search",
        "title": "Primary Caregiver Paid Parental Leave",
        "query": "I just welcomed a new child—how many weeks of paid leave do primary caregivers get?",
        "source_doc": "01_Global_PTO_and_Leave_Policy.pdf",
        "solution": "Primary caregivers receive 16 weeks of 100% paid parental leave (eligible after 90 days tenure).",
    },
    {
        "id": "Q2",
        "category": "Keyword & Form Code",
        "title": "Form EXP-402B & Submission Deadline",
        "query": "What is Form EXP-402B used for and what is the submission deadline?",
        "source_doc": "03_Expense_and_Travel_Reimbursement_Policy.pdf",
        "solution": "Supplemental expense itemization for expenses exceeding $500. Deadline is 30 calendar days post-travel.",
    },
    {
        "id": "Q3",
        "category": "Multi-Column Table Parsing",
        "title": "PPO vs. HDHP Deductible and HSA",
        "query": "Compare the family deductible and employer HSA contribution between the PPO and HDHP medical plans.",
        "source_doc": "02_2026_Benefits_and_Healthcare_Guide.pdf",
        "solution": "PPO: Family deductible $1,500, HSA employer contribution $0. HDHP: Family deductible $3,000, HSA employer contribution $1,200.",
    },
    {
        "id": "Q4",
        "category": "Agentic & Transactional Reasoning",
        "title": "Remote Work from Japan + PTO for EMP-1042",
        "query": "I am employee EMP-1042. Can I work remotely from Japan for 15 workdays next month, and do I have enough PTO balance to take 5 vacation days right after?",
        "source_doc": "04_Remote_Work_and_Equipment_Stipend_FAQ.pdf + HRIS DB",
        "solution": "Yes, approved: Alex Johnson has used 4/20 remote work days (16 days left). PTO balance is 14 days, which safely covers the 5 days requested (leaving 9 days).",
    },
    {
        "id": "Q5",
        "category": "FLSA Overtime & Equity",
        "title": "FLSA Overtime Multiplier & RSU Vesting",
        "query": "What is the overtime rate for non-exempt employees working over 40 hours, and what is the vesting schedule for RSUs?",
        "source_doc": "05_Global_Compensation_Overtime_and_Bonus_Plan.pdf",
        "solution": "Overtime is 1.5x regular hourly rate for hours over 40. RSU equity grants vest over 4 years with a 1-year cliff (25%) followed by 6.25% quarterly.",
    },
    {
        "id": "Q6",
        "category": "Anti-Corruption & Whistleblower",
        "title": "Gift Threshold & EthicsPoint Hotline",
        "query": "What is the monetary limit for business gifts from partners, and what number can I call to report ethics violations anonymously?",
        "source_doc": "06_Global_Code_of_Conduct_Anti_Corruption_and_Whistleblowing.pdf",
        "solution": "Gifts under $100 allowed; gifts $100-$250 require Form ETH-101 disclosure; gifts over $250 strictly prohibited. 24/7 confidential EthicsPoint hotline is 1-800-461-9330.",
    },
    {
        "id": "Q7",
        "category": "Talent Calibration & Promotion",
        "title": "Promotion Eligibility & Merit Increase",
        "query": "What are the promotion requirements from one level to the next, and what form must a director submit?",
        "source_doc": "07_Performance_Calibration_Promotion_and_PIP_Guidelines.pdf",
        "solution": "Minimum 12 months in current level, at least 2 consecutive cycles of Exceeds/Outstanding ratings, and submission of Promotion Dossier Form PRM-301.",
    },
    {
        "id": "Q8",
        "category": "Cybersecurity & Access Control",
        "title": "Password Complexity & Screen Lock Timeout",
        "query": "What are the password complexity requirements, rotation period, and inactivity screen lock timeout?",
        "source_doc": "08_Information_Security_BYOD_and_Acceptable_Use_Policy.pdf",
        "solution": "Minimum 14 characters with uppercase, lowercase, numbers, and symbols; mandatory 90-day rotation; and automatic screen lock after 5 minutes of inactivity.",
    },
    {
        "id": "Q9",
        "category": "Education & Retention Covenants",
        "title": "Annual Learning Stipend & Tuition Agreement",
        "query": "How much is the annual individual learning stipend, and what is the post-completion retention requirement for tuition assistance?",
        "source_doc": "09_Learning_Development_and_Tuition_Assistance_Program.pdf",
        "solution": "$2,500 annual stipend via Form LND-201. Tuition assistance (up to $5,250 IRS Sec 127) requires a 12-month retention covenant (100% repayment within 6 mos, 50% in 7-12 mos).",
    },
    {
        "id": "Q10",
        "category": "Separation & Severance",
        "title": "Involuntary Severance & PTO Payout Formula",
        "query": "What is the standard severance formula for involuntary separation, and how is accrued unused PTO paid out?",
        "source_doc": "10_Offboarding_Severance_and_Separation_Policy.pdf",
        "solution": "2 weeks base salary per full year of continuous service (min 4 weeks, max 26 weeks) plus 3 months COBRA subsidy. PTO payout = Unused Hours × (Annual Base / 2,080).",
    },
]
